# Generated by Django 2.1.5 on 2021-09-06 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPass',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.MyUser')),
                ('cardholdername', models.CharField(max_length=120)),
                ('number', models.BinaryField(null=True)),
                ('numberkey', models.BinaryField(null=True)),
                ('brand', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American Express', 'American Express'), ('Maestro', 'Maestro'), ('UnionPay', 'UnionPay'), ('other', 'other')], max_length=120, null=True)),
            ],
            bases=('task.myuser',),
        ),
        migrations.CreateModel(
            name='LoginPass',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.MyUser')),
                ('username', models.CharField(max_length=120)),
                ('password', models.BinaryField(null=True)),
                ('passwordkey', models.BinaryField(null=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            bases=('task.myuser',),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loginpass', to=settings.AUTH_USER_MODEL),
        ),
    ]
