# Generated by Django 2.1.5 on 2021-09-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginpass',
            name='updated',
        ),
        migrations.AddField(
            model_name='creditpass',
            name='cvv',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='creditpass',
            name='cvvkey',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='creditpass',
            name='expirationmonth',
            field=models.CharField(choices=[('01 - January', 'monthchoices'), ('02 - February', 'monthchoices'), ('03 - March', 'monthchoices'), ('04 - April', 'monthchoices'), ('05 - May', 'monthchoices'), ('06 - June', 'monthchoices'), ('07 - July', 'monthchoices'), ('08 - August', 'monthchoices'), ('09 - September', 'monthchoices'), ('10 - October', 'monthchoices'), ('11 - November', 'monthchoices'), ('12 - December', 'monthchoices')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='creditpass',
            name='expirationyear',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='creditpass',
            name='pin',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='creditpass',
            name='pinkey',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creditpass',
            name='brand',
            field=models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('American Express', 'American Express'), ('Maestro', 'Maestro'), ('UnionPay', 'UnionPay'), ('Other', 'Other')], max_length=120, null=True),
        ),
    ]
