# Generated by Django 2.1.5 on 2021-09-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210907_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesPass',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task.MyUser')),
                ('notes', models.BinaryField(null=True)),
                ('noteskey', models.BinaryField(null=True)),
            ],
            bases=('task.myuser',),
        ),
    ]
