# Generated by Django 2.1.5 on 2021-09-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_notespass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpass',
            name='cvvkey',
        ),
        migrations.RemoveField(
            model_name='creditpass',
            name='numberkey',
        ),
        migrations.RemoveField(
            model_name='creditpass',
            name='pinkey',
        ),
        migrations.RemoveField(
            model_name='loginpass',
            name='passwordkey',
        ),
    ]
